CREATE DATABASE tasksdb;

-- \c tasksdb;

CREATE TABLE IF NOT EXISTS tasks(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(200),
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "public"."test" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 99999999
START 3
CACHE 1
),
  "data" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Primary Key structure for table test
-- ----------------------------
ALTER TABLE "public"."test" ADD CONSTRAINT "test_pkey" PRIMARY KEY ("id");

INSERT INTO tasks(title, description) VALUES ('first task', 'some description');

-- 

SELECT * FROM tasks;